FROM tensorflow/tensorflow

RUN pip install keras && \
    pip install h5py && \
    pip install pandas && \
    pip install flask && \
    pip install flask_json

RUN rm -r /notebooks

COPY server/app.py app.py
